Asp.Net-PartialViews/Models/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
    }
}

Asp.Net-PartialViews/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.Models
{
    public class Product:BaseEntity
    {
        public string Name { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal Price { get; set; }
        public string ProductImage { get; set; }
    }
}

Asp.Net-PartialViews/ViewModels/AccessoriesVM.cs
using Asp.Net_PartialViews.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.ViewModels
{
    public class AccessoriesVM
    {
        public IEnumerable<Product> Products { get; set; }
    }
}

Asp.Net-PartialViews/ViewModels/BasketDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.ViewModels
{
    public class BasketDetail
    {
        public string Name { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
    }
}

Asp.Net-PartialViews/ViewModels/BasketDetailVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.ViewModels
{
    public class BasketDetailVM
    {
        public string Name { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public int Count { get; set; }
    }
}

Asp.Net-PartialViews/ViewModels/BasketVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.ViewModels
{
    public class BasketVM
    {
        public int Id { get; set; }
        public int Count { get; set; }
    }
}

Asp.Net-PartialViews/Controllers/AccessoriesController.cs
using Asp.Net_PartialViews.Data;
using Asp.Net_PartialViews.Models;
using Asp.Net_PartialViews.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.Controllers
{
    public class AccessoriesController : Controller
    {
        private AppDbContext _context;

        public AccessoriesController(AppDbContext context)
        {
            _context = context;
        }
        
        public async Task<IActionResult> Index()
        {

            IEnumerable<Product> products = await _context.Products.Where(m=>!m.IsDeleted).Take(3).ToListAsync();
            ViewBag.count = await _context.Products.Where(m => !m.IsDeleted).CountAsync();
            AccessoriesVM accessoriesVM = new AccessoriesVM {
                Products = products,
            };

            return View(accessoriesVM);
        }
        public async Task<IActionResult> LoadMore(int skip)
        {
            IEnumerable<Product> products = await _context.Products.Where(m => !m.IsDeleted).Skip(skip).Take(3).ToListAsync();

            return PartialView("_ProductsPartial", products);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            //var dbProduct = _context.Products.FirstOrDefaultAsync();
            var dbProduct = await _context.Products.FindAsync(id);

            if (dbProduct == null)
            {
                return BadRequest();
            }

            List<BasketVM> baskets = GetBasket();

            Updatebasket(baskets, dbProduct.Id);
           

            Response.Cookies.Append("basket", JsonConvert.SerializeObject(baskets));
            return Json(new { succes = true, responseText = "Your messagesfuly sent!" });
            
        }

        private void Updatebasket(List<BasketVM> baskets,int id)
        {
            int basketCount = baskets.Count;
            basketCount = 1;

            BasketVM existProduct = baskets.Find(m => m.Id == id);

            if (existProduct != null)
            {
                existProduct.Count++;
            }
            else
            {
                baskets.Add(new BasketVM
                {
                    Id = id,
                    Count = basketCount
                });
            }
        }
        private List<BasketVM> GetBasket()
        {
            List<BasketVM> baskets;

            if (Request.Cookies["basket"] != null)
            {
                baskets = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies["basket"]);
            }
            else
            {
                baskets = new List<BasketVM>();
            }

            return baskets;
        }
    }
}

Asp.Net-PartialViews/Controllers/BasketController.cs
using Asp.Net_PartialViews.Data;
using Asp.Net_PartialViews.Models;
using Asp.Net_PartialViews.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.Controllers
{
    public class BasketController : Controller
    {
        private AppDbContext _context;

        public BasketController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<BasketVM> basketItems = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies["basket"]);
            List<BasketDetailVM> basketDetails = new List<BasketDetailVM>();

            foreach (var item in basketItems)
            {
                Product product = await _context.Products
                    .Where(m => m.Id == item.Id && m.IsDeleted == false).FirstOrDefaultAsync();

                BasketDetailVM newBasketDetails = new BasketDetailVM  { 
                     Name = product.Name,
                     Image = product.ProductImage,
                     Price = product.Price,
                     Count = item.Count,
                     Total = item.Count * product.Price
                };

                basketDetails.Add(newBasketDetails);

            }
            return View(basketDetails);
        }
    }
}

Asp.Net-PartialViews/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_PartialViews.Controllers
{
    public class HomeController : Controller
    {
        

        public IActionResult Index()
        {
            return View();
        }

    }
}

Asp.Net-PartialViews/Views/Accessories/Index.cshtml
@model AccessoriesVM
@{
    ViewData["Title"] = "Accessories Page";
}

<main>
    <section id="product-list">
        <div class="container-fluid">
            <div class="row">
                <div class="col-3">
                    <div class="row">
                        <div class="product-filter">
                            <div class="search">
                                <input type="text" placeholder="Search products..." />
                            </div>

                            <div class="brand">
                                <h6><b>Brands</b></h6>
                                <input type="text" placeholder="Search products..." /><br />
                                <input type="checkbox" />
                                <label>Insignis </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>Samsung </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>HP </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>Metris </label><span class="count">4</span><br />
                            </div>

                            <div class="type">
                                <h6><b>Type</b></h6>

                                <input type="checkbox" placeholder="Search products..." />
                                <label>Trend cases </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>ULt protection cases </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>Ink cartridges </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>Business cases </label><span class="count">4</span><br />
                            </div>

                            <div class="category">
                                <h6><b>Category</b></h6>
                                <input type="text" placeholder="Search products..." /><br />
                                <input type="checkbox" />
                                <label>Appliances </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>Computers & Tablets </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>Cell Phones </label><span class="count">4</span><br />

                                <input type="checkbox" />
                                <label>Audio </label><span class="count">4</span><br />
                            </div>

                            <div class="price">
                                <h6><b>Price</b></h6>

                                <input type="radio" name="price" />
                                <label>Below $10 </label><br />

                                <input type="radio" name="price" />
                                <label>$10 - $100 </label><br />

                                <input type="radio" name="price" />
                                <label>$100 -$500 </label><br />

                                <input type="radio" name="price" />
                                <label>Above $500 </label><br />
                                <h6><b>Enter Price Range</b></h6>
                                <input type="number" placeholder="1" />

                                <input type="number" placeholder="$500" />
                                <button><a href="">Go</a></button>
                            </div>

                            <div class="rating">
                                <h6><b>Rating Menu</b></h6>
                                <li>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span><span class="count">4</span>
                                </li>
                                <li>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span><span class="count">4</span>
                                </li>
                                <li>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span><span class="count">4</span>
                                </li>
                                <li>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span><span class="count">4</span>
                                </li>
                                <li>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span><span class="count">4</span>
                                </li>
                            </div>

                            <div class="clear">
                                <button>
                                    <a href="">Clear all filters</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-9">
                    <div class="row">
                        <div class="selection">
                            <select name="price" id="select-price" class="price">
                                <option value="">Featured</option>
                                <option value="dog">Lowest prices</option>
                                <option value="cat">Highest prices</option>
                            </select>
                            <span>18,046 results found in 10ms</span>
                        </div>
                    </div>

                    <div class="product-cards">
                        <input type="hidden" id="product-count" value="@ViewBag.count" />
                        <div class="row" id="parent-products">
                            <partial name="_ProductsPartial" model="@Model.Products" />
                        </div>

                    </div>

                    
                    <div class="show-more d-flex justify-content-center my-2 mb-2 w-100">
                        <button class="btn btn-primary">Show more ...</button>
                    </div>
                    <div class="row">
                        <div class="pagination">
                            <a href="#" class="blocks">&laquo;</a>
                            <a href="#" class="blocks active">1</a>
                            <a href="#" class="blocks">2</a>
                            <a href="#" class="blocks">3</a>
                            <a href="#" class="blocks">4</a>
                            <a href="#" class="blocks">5</a>

                            <a href="#" class="blocks">&raquo;</a>
                        </div>
                    </div>

                </div>
               
            </div>
           
        </div>
    </section>
</main>

Asp.Net-PartialViews/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Asp.Net-PartialViews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Accessories</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css" />

    <link rel="stylesheet" href="~/assets/css/accessories/accessories.css" />
</head>

<body>
    <header>
        <section id="top-area">
            <div class="my-container">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12 d-flex">
                        <div class="language">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle button1"
                                        type="button"
                                        id="dropdownMenuButton1"
                                        data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                    English 
                                </button>
                                <ul class="dropdown-menu"
                                    aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" href="#">English</a></li>
                                    <li><a class="dropdown-item" href="#">French</a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="country">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle button2"
                                        type="button"
                                        id="dropdownMenuButton1"
                                        data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                    USD
                                </button>
                                <ul class="dropdown-menu"
                                    aria-labelledby="dropdownMenuButton1">
                                    <li>
                                        <a class="dropdown-item" href="">
                                            <img src="~/assets/images/home/Flag-India.jpg" /><span>INR</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="">
                                            <img src="~/assets/images/home/220px-Flag_of_the_United_States.svg.png" /><span>USD</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="">
                                            <img src="~/assets/images/home/Flag_of_New_Zealand.svg.png" /><span>NZD</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="">
                                            <img src="~/assets/images/home/Flag_of_Germany.svg.png" /><span>GMD</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="">
                                            <img src="~/assets/images/home/1200px-Flag_of_Israel.svg.png" /><span>ILR</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="">
                                            <img src="~/assets/images/home/Flag_of_France.svg.png" /><span>EUR</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="top-area-logo">
                            <img src="~/assets/images/about/download.png" alt="logo" />
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="icons">
                            <div class="basket">
                                <a asp-controller="Basket" asp-action="Index">
                                    <div class="basket-bg">
                                        <i class="fa-solid fa-cart-shopping"></i>
                                    </div>
                                    <div class="basket-circles"><sup>0</sup></div>
                                </a>
                            </div>

                            <div class="heart">
                                <div class="favori-bg">
                                    <i class="fa-solid fa-heart"></i>
                                </div>
                                <div class="heart-circles"><sup></sup></div>
                            </div>

                            <div class="profile-img">
                                <a href="./profile.html">
                                    <img src="~/assets/images/home/avatar.jfif" alt="profile" />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="nav-area">
            <div class="my-container">
                <div class="col-12">
                    <nav>
                        <div class="search">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </div>
                        <ul class="navbar-list">
                            <li>
                                <a class="hov" href="./home.html">HOME</a>
                                <ul class="submenu home">
                                    <li><a href="#">HOME ONE</a></li>
                                    <li><a href="#">HOME TWO</a></li>
                                    <li><a href="#">HOME THREE</a></li>
                                </ul>
                            </li>
                            <li>
                                <a class="hov" href="#">SHOP</a>
                                <ul class="submenu shop">
                                    <li><a href="./product.html">PRODUCT DETAIL</a></li>
                                    <li><a href="#">CART</a></li>
                                    <li><a href="#">CHECKOUT</a></li>
                                    <li><a href="#">PAYMENT</a></li>
                                </ul>
                            </li>
                            <li>
                                <a class="hov" href="./accessories.html">ACCESSORIES</a>
                            </li>
                            <li>
                                <a class="hov" href="#">CATEGORIES</a>
                                <ul class="submenu categories">
                                    <div class="product1">
                                        <h5>MEN</h5>
                                        <hr />
                                    <li><a href="#">- T-Shirts</a></li>
                                    <li><a href="#">- Jeans</a></li>
                                    <li><a href="#">- Shoes</a></li>
                                    <li><a href="#">- Wallet</a></li>
                </div>
                <div class="product1">
                    <h5>WOMEN</h5>
                    <hr />
                    <li><a href="#">- Western Wear</a></li>
                    <li><a href="#">- Ethnic Wear</a></li>
                    <li><a href="#">- Sports Wear</a></li>
                </div>
                <div class="product1">
                    <h5>GADGETS</h5>
                    <hr />
                    <li><a href="#">- HeadPhones</a></li>
                    <li><a href="#">- Laptop</a></li>
                    <li><a href="#">- Speaker</a></li>
                    <li><a href="#">- Watch</a></li>
                </div>
                <div class="product1">
                    <h5>ACCESSORIES</h5>
                    <hr />
                    <li><a href="#">- Jewellery</a></li>
                    <li><a href="#">- Belts</a></li>
                    <li><a href="#">- HandBag</a></li>
                </div>
                </ul>
                </li>
                <li><a class="hov" href="./about.html">ABOUT US</a></li>
                <li><a class="hov" href="#">CONTACT US</a></li>
                <li><a class="hov admin" href="#">ADMIN PANEL</a></li>
                </ul>
                </nav>
            </div>
            </div>
        </section>

        <section id="cover">
            <div class="back-img">
                <h1>Product Details</h1>
            </div>
        </section>
    </header>
    @RenderBody()
    <footer>
        <section id="footer">
            <div class="container-fluid">
                <div class="row" style="height: 100px">
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="about-comp">
                            <h6>Abput Company</h6>
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                                cumque eum, blanditiis nesciunt architecto nemo.
                            </p>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 col-sm-12">
                        <div class="about">
                            <h6>About</h6>
                            <ul>
                                <li>about us</li>
                                <li>terms and conditionp</li>
                                <li>privacy</li>
                                <li>FAQ</li>
                                <li>Contact us</li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 col-sm-12">
                        <div class="session">
                            <h6>Session</h6>
                            <ul>
                                <li>Sign in</li>
                                <li>Register</li>
                                <li>Forget password</li>
                                <li>Thank you</li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 col-sm-12">
                        <div class="categories">
                            <h6>Categories</h6>
                            <ul>
                                <li>men</li>
                                <li>women</li>
                                <li>accesories</li>
                                <li>Gadgets/li></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 col-sm-12">
                        <div class="social">
                            <h6>Social</h6>
                            <ul>
                                <li>facebook</li>
                                <li>twitter</li>
                                <li>instagram</li>
                                <li>google plus</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="copyright">
            <div class="copyright">
                <div class="img">
                    <img src="~/assets/images/home/cards.png" alt="" />
                </div>
                <div class="text">
                    <p>
                        © All Rights Reversed | Made With Love by IRON NETWORK for better
                        Web
                    </p>
                </div>
            </div>
        </section>
    </footer>


    <script src="https://kit.fontawesome.com/97c11cf46f.js"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"
            integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>

    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="~/assets/js/accessories/accessories.js"></script>

</body>
</html>

Asp.Net-PartialViews/Views/Shared/_ProductsPartial.cshtml
@model IEnumerable<Product>


@foreach (var item in Model)
{
    <div class="col-lg-4 col-12">
        <div class="product-card">
            <div class="img">
                <img src="~/assets/images/home/@item.ProductImage" alt="" />

                <div class="price">$@item.Price</div>
            </div>
            <div class="title">
                <form asp-controller="Accessories" asp-action="AddBasket" asp-route-id="@item.Id" method="post" class="basketForm">
                    <button type="submit" style="border:none">
                        <div class="cart">
                            <i class="fa-solid fa-cart-shopping">
                            
                            </i>
                        </div>
                    </button>
                      
                    
                </form>
                
               
                <h6>@item.Name</h6>
                <ul>
                    <li><i class="fa-solid fa-star"></i></li>
                    <li><i class="fa-solid fa-star"></i></li>
                    <li><i class="fa-solid fa-star"></i></li>
                    <li><i class="fa-solid fa-star"></i></li>
                    <li><i class="fa-solid fa-star"></i></li>
                </ul>
            </div>
            <div class="icons">
                <div class="heart">
                    <i class="fa-solid fa-heart"></i>
                </div>
                <div class="eye">
                    <i class="fa-solid fa-eye"></i>
                </div>
            </div>
        </div>
    </div>
}